/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ArticleDetail: typeof import('./components/ArticleDetail.vue')['default']
    ArticleShow: typeof import('./components/ArticleShow.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Markdown: typeof import('./components/Markdown.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectImage: typeof import('./components/SelectImage.vue')['default']
  }
}
