-- ALTER TABLE article_comment
-- DROP
-- FOREIGN KEY FK7t9jb8hdp8dm8scqhx0hgbajk;
--
-- ALTER TABLE article_comment
-- DROP
-- FOREIGN KEY FKghmocqkgqs5tkmucf5putw64t;
--
-- DROP TABLE article_comment;
